### ISSUE TITLE
pstree shows differently.

### ISSUE THREAD

**Issue by alex216** [rask24/pipex#37]
### Issue: 
pstree shows differently.

### Description:
```
$(./pipex infile "sleep 42" "sleep 41" /dev/stdout) &
[1] 91818
$pstree 91818
--- 91818 xxx sleep 41
```
whereas
```
$(< infile sleep 42 | sleep 41 > /dev/stdout) &
[1] 91313
$pstree 91313
-+= 94313 xxx bash
 |--- 94314 xxx sleep 42
 \--- 94315 xxx sleep 41
```

### Additional Notes:
if remove all `waitpid()` and add
```
while (wait(NULL) != -1)
    continue;
```
just before main return, pstree result shows like original pipe.

```
$ (./pipex infile "sleep 42" "sleep 41" /dev/stdout) &
[1] 94615
$ pstree 94615
-+= 94313 xxx bash
 |--- 94314 xxx sleep 42
 \--- 94315 xxx sleep 41
```

[Any additional information or considerations about the fix]
losing stability of watching all child procs separately.

[Potential side effects or impacts]
Unknown.

[Future work or follow-up tasks]
Unknown.

Verification Steps:
To verify the bug fix, please follow these steps:

[Step 1] remove all `waitpid()`
[Step 2] remove `WIFEXITED`
[Step 3] add `wait` at the end of main

If everything looks good, please close the issue. If you encounter any issues or have further questions, feel free to comment below.

Thank you!

**Comment by rask24** [comment]
@alex216 
You're right, bash creates all processes at once and then waits for them. I felt it was necessary to return the exit status of the last child process from the main function, so I decided to store all the child PIDs and use waitpid for them all at the end of main.

However, this caused a bug where error messages were getting mixed up. After investigating, I found out that ft_dprintf internally called the write function per character. By changing the implementation to create the entire error message string first and then write the whole line at once, I was able to fix all the bugs.

Thanks for reporting the issue!
